### ISSUE TITLE
Secured protocol cannot be configured to http transport sender in toml file

### ISSUE THREAD

**Issue by madushadhanushka** [wso2/micro-integrator#1059] opened 2019-10-23 06:11 UTC
**Description:**
Currently, the secured protocol can be only configured for Http transport listeners. It does not support for Http transport sender. 

The following workaround can be used as a temporary fix.

```toml
[transport.http]
sender.parameter.HttpsProtocols = "TLSv1,TLSv1.1,TLSv1.2"
```

**Comment by sdkottegoda** [comment] 2019-12-06 07:26
Closing since the issue is fixed with the above PR.

**Closed by sdkottegoda** 2019-12-06 07:26 UTC
Labels: 1.1.0, Priority/High, bug
