### ISSUE TITLE
Error while logging into WSO2 Micro Integrator Dashboard.

### ISSUE THREAD

**Issue by Nethminiromina** [wso2/micro-integrator#1384] opened 2020-04-10 11:50 UTC
**Description:**
Following error occurred while logging into WSO2 MI Dashboard.
`Unknown error occurred!`
![image](https://user-images.githubusercontent.com/26083113/78987713-6591b400-7b4c-11ea-9ae8-f39248b45e76.png)

**Affected Product Version:**
WSO2 EI 7.0.2

**OS, DB, other environment details and versions:**
macOS    

**Steps to reproduce:**

1. Start MI packages as below. `sh micro-integrator.sh -DenableManagementApi`
2. Visit https://localhost:9164/magagement and trust the certificate.
3. Start dashboard `sh dashboard.sh`
4. Visit https://127.0.0.1:9743/dashboard/login and try to log in.
No error logs were printed in the terminal, but an error was displayed in the dashboard as in the above screenshot. `Unknown error occurred!`

**Comment by Vathsan** [comment] 2020-04-15 03:00
When logging in to the dashboard try giving the Host as your IP, which is 192.168.1.9

**Comment by Nethminiromina** [comment] 2020-04-15 04:25
Hi @Vathsan 
Yes I tried using the IP 192.168.1.9 `(192.168.1.9:9743/dashboard)`

**Comment by Vathsan** [comment] 2020-04-15 14:29
Hi @Nethminiromina ,

If you direct the browser to https://**localhost**:9164/management and add the site as trusted (given MI hostname is localhost), then you should be able to login to the MI dashboard with the host **localhost** (specify localhost as host while logging in to the dashboard).

If you add the micro integrator instance to the browser as a trusted source by directing the browser to https://{**some_ip**}:9164/management then, the MI dashboard should be logged in with host **some_ip**.

Please check whether the hostname of the certificate that you trust and the host you provide during MI dashboard log in are same. If you access `192.168.1.9:9743/dashboard` and specify the host as 192.168.1.9 then you need to visit `https://192.168.1.9:9164/magagement` to trust the certificate.

**Comment by sdkottegoda** [comment] 2020-04-23 11:23
We are closing the issue since the resolution has been provided. Please re-open for further assistance.

**Comment by sajithaliyanage** [comment] 2020-06-17 07:11
The same issue can experience in the MI-1.1.0-alpha release. 

**Steps to reproduce:**

- Start the dashboard by executing `sh dashboard.sh`. it logs ```Web app 'dashboard' is available at 'https://127.0.0.1:9743/dashboard'``` in the console. 
- Visit https://127.0.0.1:9743/dashboard/login and try to log in.
- Once we pressed the login button, it redirects to the `https://localhost:9164/magagement` to trust the certificates. 

We can overcome this issue by changing the dashboard URL as `https://localhost:9743/dashboard` instead of `https://127.0.0.1:9743/dashboard`

**Comment by chanikag** [comment] 2020-06-18 04:20
I tried to reproduce the issue in the dashboard which is built from the master branch and couldn't reproduce.

**Comment by sachithKay** [comment] 2020-06-22 06:10
Please check the browser console logs and add it to this issue (as text or screenshots) if the issue is reproduced.

**Comment by sdkottegoda** [comment] 2020-07-06 10:48
Please re-open with the resources mentioned by sachitKay.

**Closed by sdkottegoda** 2020-07-06 10:48 UTC
Labels: Priority/High, Resolution/Cannot Reproduce, Severity/Critical, Type/Bug
