### ISSUE TITLE
Issue when Re Deploying Capp with message stores in Cluster

### ISSUE THREAD

**Issue by malakaganga** [wso2/micro-integrator#1680] opened 2020-06-15 07:57 UTC
**Description:**
When Re Deploying Capp with MessageStores (deployed in a cluster)

Follwoing exception throws,

```
[2020-06-15 13:11:14,533] ERROR {AbstractSynapseArtifactDeployer} - Deployment of synapse artifact failed. Error reading /home/malaka/MyFolder/esb_patch_5/TestMICoordination/Node1/wso2mi-1.2.0-SNAPSHOT/tmp/carbonapps/-1234/1592206874101MSMP_ProjectCompositeApplication_1.0.0.car/failoverMsgStore_1.0.0/failoverMsgStore-1.0.0.xml : Message Store Deployment from the file : /home/malaka/MyFolder/esb_patch_5/TestMICoordination/Node1/wso2mi-1.2.0-SNAPSHOT/tmp/carbonapps/-1234/1592206874101MSMP_ProjectCompositeApplication_1.0.0.car/failoverMsgStore_1.0.0/failoverMsgStore-1.0.0.xml : Failed. org.apache.axis2.deployment.DeploymentException: Message Store Deployment from the file : /home/malaka/MyFolder/esb_patch_5/TestMICoordination/Node1/wso2mi-1.2.0-SNAPSHOT/tmp/carbonapps/-1234/1592206874101MSMP_ProjectCompositeApplication_1.0.0.car/failoverMsgStore_1.0.0/failoverMsgStore-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:210)
	at org.wso2.micro.integrator.initializer.deployment.synapse.deployer.SynapseAppDeployer.deployArtifactType(SynapseAppDeployer.java:1106)
	at org.wso2.micro.integrator.initializer.deployment.synapse.deployer.SynapseAppDeployer.deployArtifacts(SynapseAppDeployer.java:134)
	at org.wso2.micro.integrator.initializer.deployment.application.deployer.CappDeployer.deployCarbonApps(CappDeployer.java:141)
	at org.wso2.micro.integrator.initializer.deployment.application.deployer.CappDeployer.deploy(CappDeployer.java:99)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:153)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.synapse.deployers.SynapseArtifactDeploymentException: Message Store Deployment from the file : /home/malaka/MyFolder/esb_patch_5/TestMICoordination/Node1/wso2mi-1.2.0-SNAPSHOT/tmp/carbonapps/-1234/1592206874101MSMP_ProjectCompositeApplication_1.0.0.car/failoverMsgStore_1.0.0/failoverMsgStore-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.handleSynapseArtifactDeploymentError(AbstractSynapseArtifactDeployer.java:483)
	at org.apache.synapse.deployers.MessageStoreDeployer.deploySynapseArtifact(MessageStoreDeployer.java:77)
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:200)
	... 19 more
Caused by: org.apache.synapse.SynapseException: Duplicate message store : failoverMsgStore
	at org.apache.synapse.config.SynapseConfiguration.handleException(SynapseConfiguration.java:1667)
	at org.apache.synapse.config.SynapseConfiguration.addMessageStore(SynapseConfiguration.java:1815)
	at org.apache.synapse.deployers.MessageStoreDeployer.deploySynapseArtifact(MessageStoreDeployer.java:63)
	... 20 more

[2020-06-15 13:11:14,535] ERROR {CappDeployer} - Error occurred while deploying the Carbon application: /home/malaka/MyFolder/esb_patch_5/TestMICoordination/Node1/wso2mi-1.2.0-SNAPSHOT/repository/deployment/server/carbonapps/MSMP_ProjectCompositeApplication_1.0.0.car org.apache.axis2.deployment.DeploymentException: Message Store Deployment from the file : /home/malaka/MyFolder/esb_patch_5/TestMICoordination/Node1/wso2mi-1.2.0-SNAPSHOT/tmp/carbonapps/-1234/1592206874101MSMP_ProjectCompositeApplication_1.0.0.car/failoverMsgStore_1.0.0/failoverMsgStore-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:222)
	at org.wso2.micro.integrator.initializer.deployment.synapse.deployer.SynapseAppDeployer.deployArtifactType(SynapseAppDeployer.java:1106)
	at org.wso2.micro.integrator.initializer.deployment.synapse.deployer.SynapseAppDeployer.deployArtifacts(SynapseAppDeployer.java:134)
	at org.wso2.micro.integrator.initializer.deployment.application.deployer.CappDeployer.deployCarbonApps(CappDeployer.java:141)
	at org.wso2.micro.integrator.initializer.deployment.application.deployer.CappDeployer.deploy(CappDeployer.java:99)
	at org.apache.axis2.deployment.repository.util.DeploymentFileData.deploy(DeploymentFileData.java:136)
	at org.apache.axis2.deployment.DeploymentEngine.doDeploy(DeploymentEngine.java:807)
	at org.apache.axis2.deployment.repository.util.WSInfoList.update(WSInfoList.java:153)
	at org.apache.axis2.deployment.RepositoryListener.update(RepositoryListener.java:377)
	at org.apache.axis2.deployment.RepositoryListener.checkServices(RepositoryListener.java:254)
	at org.apache.axis2.deployment.RepositoryListener.startListener(RepositoryListener.java:371)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.checkRepository(SchedulerTask.java:59)
	at org.apache.axis2.deployment.scheduler.SchedulerTask.run(SchedulerTask.java:67)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.axis2.deployment.DeploymentException: Message Store Deployment from the file : /home/malaka/MyFolder/esb_patch_5/TestMICoordination/Node1/wso2mi-1.2.0-SNAPSHOT/tmp/carbonapps/-1234/1592206874101MSMP_ProjectCompositeApplication_1.0.0.car/failoverMsgStore_1.0.0/failoverMsgStore-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:210)
	... 19 more
Caused by: org.apache.synapse.deployers.SynapseArtifactDeploymentException: Message Store Deployment from the file : /home/malaka/MyFolder/esb_patch_5/TestMICoordination/Node1/wso2mi-1.2.0-SNAPSHOT/tmp/carbonapps/-1234/1592206874101MSMP_ProjectCompositeApplication_1.0.0.car/failoverMsgStore_1.0.0/failoverMsgStore-1.0.0.xml : Failed.
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.handleSynapseArtifactDeploymentError(AbstractSynapseArtifactDeployer.java:483)
	at org.apache.synapse.deployers.MessageStoreDeployer.deploySynapseArtifact(MessageStoreDeployer.java:77)
	at org.apache.synapse.deployers.AbstractSynapseArtifactDeployer.deploy(AbstractSynapseArtifactDeployer.java:200)
	... 19 more
Caused by: org.apache.synapse.SynapseException: Duplicate message store : failoverMsgStore
	at org.apache.synapse.config.SynapseConfiguration.handleException(SynapseConfiguration.java:1667)
	at org.apache.synapse.config.SynapseConfiguration.addMessageStore(SynapseConfiguration.java:1815)
	at org.apache.synapse.deployers.MessageStoreDeployer.deploySynapseArtifact(MessageStoreDeployer.java:63)
	... 20 more

[2020-06-15 13:11:23,948]  INFO {AbstractQuartzTaskManager} - Task resumed: [ESB_TASK][MSMP_MSG_Processor_0]
```

**Comment by Nirothipan** [comment] 2020-06-18 09:12
This has happened since the tmp folder (wso2mi-1.2.0-SNAPSHOT/tmp/carbonapps/-1234/1592465680620MSMP_ProjectCompositeApplication_1.0.0.car ) where the carbon app extracted is not deleted.

Restarting the server or removing those temp files sorted the issue.

This is not reproducible and checked the carbon logs for the error and no occurrence of the following is also found https://github.com/wso2/micro-integrator/blob/master/components/org.wso2.micro.integrator.initializer/src/main/java/org/wso2/micro/integrator/initializer/deployment/application/deployer/CappDeployer.java#L493

```java
  } catch (Exception e) {
            log.error("Error occurred while trying to unDeploy  : " + carbonApp.getAppNameWithVersion());
        }
```
Hence closing the issue as this is not reproducible , please re-open if there are more solid steps to recreate the issue.

**Closed by Nirothipan** 2020-06-18 09:12 UTC
Labels: Priority/High, Severity/Blocker, Severity/Major
