### ISSUE TITLE
Issue while converting the JSON payload to XML which is derived from JSON eval operation along with payload factory mediator

### ISSUE THREAD

**Issue by riyazathali** [wso2/micro-integrator#3046] opened 2023-12-07 03:57 UTC
When we try to convert the JSON payload to XML using the Payload factory mediator we get the below error in MI 4.0.0 U2 pack.

[2023-12-06 20:28:53,264] ERROR {JsonUtil} - #toXml. Could not convert JSON Stream to XML. Cannot handle JSON input. Error>>> java.io.IOException: Illegal character: <&>
[2023-12-06 20:28:53,265] ERROR {PayloadFactoryMediator} - {proxy:JsonToXmlProxy} Error converting JSON to XML, please check your JSON Path expressions return valid JSON: 

The sample proxy logic is as below.

```
<property expression="json-eval($.)" name="Payload" scope="default" type="STRING"/>
                   <log level="custom">
                <property name="Incoming JSON==================" expression="$ctx:Payload"/>
            </log>
            <!-- Convert JSON to XML using PayloadFactory mediator -->
            <payloadFactory media-type="xml">
                <format>
                    <soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/">
                        <soapenv:Body>
                            <root>
                                <f>json</f>
                                
                                <sample><![CDATA[$1]]></sample>
                            </root>
                        </soapenv:Body>
                    </soapenv:Envelope>
                </format>
                <args>
                    
                    <arg evaluator="xml" expression="$ctx:Payload" literal="true"/>
                </args>
            </payloadFactory>
```

Thanks,
Riyazath Ali.

**Comment by GDLMadushanka** [comment] 2023-12-08 09:12
Duplicate of https://github.com/wso2/product-ei/issues/5510

**Closed by GDLMadushanka** 2023-12-08 09:12 UTC
