### ISSUE TITLE
 ei-operator-ingress loops rules indefinitely

### ISSUE THREAD

**Issue by sachithKay** [wso2/micro-integrator#2129] opened 2021-03-10 09:56 UTC
**Description:**
The created ingress loops its rules indefinitely

**Steps:**
- Create a deployment with autoIngressCreation: "true" set in integration_controller_conf.yaml
- Describe the ingress with `kubectl describe ingress ei-operator-ingress -n wso2-system`
- There will be growing list of rules.
<img width="838" alt="Screen Shot 2021-03-10 at 3 25 32 PM" src="https://user-images.githubusercontent.com/22365810/110611097-e621c000-81b4-11eb-9503-e6da22302991.png">

**Comment by abeykoon** [comment] 2021-03-15 14:47
This issue is not reproducible with the fix https://github.com/wso2/micro-integrator/issues/2133 in place.

**Comment by abeykoon** [comment] 2021-03-15 14:48
Closing due to above observation.

**Closed by abeykoon** 2021-03-15 14:48 UTC
Labels: 4.0.0, Priority/Highest, bug
