### ISSUE TITLE
Inconsistency in printing logs while using the payloadFactory mediator

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/micro-integrator#1762] opened 2020-06-29 04:11 UTC
**Description:**

1. Please find the following proxy service.

```
<?xml version="1.0" encoding="UTF-8"?>
<proxy xmlns="http://ws.apache.org/ns/synapse" name="test" startOnLoad="true" statistics="disable" trace="disable" transports="http,https">
    <target>
        <inSequence>
            <payloadFactory media-type="xml">
                <format> 
                        <values>Test123</values>
                </format>			
                <args/>
            </payloadFactory>
            <log level="full"/>
            <log>
                <property expression="//*[local-name()='values']" name="objects4"/>
            </log> 
<respond/>            
        </inSequence>
    </target>
    <description/>
</proxy>
```
2. Deploy it  inside wso2mi-1.1.0 and invoke it.

Expected result
` <values>Test123</values>`

Actual result
`Test123`
 
**Suggested Labels:**
wso2mi-1.1.0, payloadFactory

**Affected Product Version:**
wso2mi-1.1.0

**OS, DB, other environment details and versions:**    
Linnux

**Related Issues:**
https://github.com/wso2/product-ei/issues/2092

**Comment by Vathsan** [comment] 2020-07-20 13:08
Could not reproduce the issue in both MI 1.1.0 and MI 1.2.0-beta packs using the above configuration. We get the following as response, 
`<values xmlns="http://ws.apache.org/ns/synapse">Test123</values>`
and the following gets logged from the log mediators,
```
[2020-07-20 18:37:22,016]  INFO {org.apache.synapse.mediators.builtin.LogMediator} - To: /services/test, MessageID: urn:uuid:94096fb9-be1a-4ba9-9f80-b576c2f33e3f, Direction: request, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Body><values xmlns="http://ws.apache.org/ns/synapse">Test123</values></soapenv:Body></soapenv:Envelope>

[2020-07-20 18:37:22,036]  INFO {org.apache.synapse.mediators.builtin.LogMediator} - To: /services/test, MessageID: urn:uuid:94096fb9-be1a-4ba9-9f80-b576c2f33e3f, Direction: request, objects4 = Test123
```
Hence closing this issue.

**Closed by Vathsan** 2020-07-20 13:08 UTC
Labels: Priority/High, Severity/Major
