### ISSUE TITLE
Read environment variables set to the container as java System properties

### ISSUE THREAD

**Issue by abeykoon** [wso2/micro-integrator#1114] opened 2020-01-09 11:29 UTC
**Description:**

When we start WSO2 MI based image as a Docker container, we can pass environment variables as below. 

```
docker run -d -p 8290:8290 -e debug '5005' sampleproxy:1.0.0
```
However, it is not read by MI server as a passed variable. It will be a useful feature if we read environment variables set to the container as arguments to the MI server script. 

**Affected Product Version:**
MI 1.1.0

**OS, DB, other environment details and versions:**  
N/A

**Comment by abeykoon** [comment] 2020-01-09 11:30
For java params, it is said we can pass like below. 
```
docker run -p 8290:8290 -p 9164:9164 -e   JAVA_OPTS="-DenableManagementApi=true" sampleproxy:1.0.0
```

**Comment by sdkottegoda** [comment] 2020-02-27 04:38
We can start MI-1.0.0 in the debug mode as follows:
```docker run -it -p 8290:8290 -p 8253:8253 -p 5005:5005 --name another-micro-integrator wso2/micro-integrator:1.0.0 -debug 5005
```
However this does not work in MI-1.1.0 we need to look into why it happens and update the documentation in [Docker Hub](https://hub.docker.com/repository/docker/wso2/micro-integrator) with the following once the issue is resolved.

## Pass arguments during server startup

### Running in debug mode

To start a Docker container instance of the Micro Integrator in debug mode (assuming 5005 to be the remote debugging port),
use the following command:

```console
$ docker run -it -p 8290:8290 -p 8253:8253 -p 5005:5005 --name another-micro-integrator wso2/micro-integrator:x.x.x -debug 5005
```

**Comment by Vathsan** [comment] 2020-03-10 09:38
The issue in enabling debug mode is fixed in https://github.com/wso2/micro-integrator/pull/1209.
We can start MI-1.1.0 in the debug mode as follows:
`docker run -p 8290:8290 -p 5005:5005 wso2/micro-integrator:1.1.0 -debug 5005`

**Comment by Vathsan** [comment] 2020-03-20 06:21
The issue in starting MI in debug mode is fixed now. We can start MI in debug mode as below,
`docker run -p 8290:8290 -p 5005:5005 wso2/micro-integrator:1.1.0 -debug 5005`

Also, java params can be passed to the container as environment variables as below,
`docker run -p 8290:8290 -p 9164:9164 -e JAVA_OPTS="-DenableManagementApi=true" wso2/micro-integrator:1.2.0-m1`

Hence resolving the issue.

**Closed by Vathsan** 2020-03-20 06:21 UTC
Labels: Docker, Priority/High, Severity/Major
