### ISSUE TITLE
microintegrator dashboard not showing the log files details

### ISSUE THREAD

**Issue by uarulraj486** [wso2/micro-integrator#2537] opened 2021-12-08 05:42 UTC
**Description:**

microintegrator4.0 dashboard not showing the log files details
**Suggested Labels:**

![image](https://user-images.githubusercontent.com/57382800/145154260-844899f7-a574-4e2b-8a3d-7537627b3602.png)

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

Started the microintegrator.bat
started the microintegrator- dashboard dashboard.bat
But it is not showing the logfiles section

**Related Issues:**

**Comment by sachithKay** [comment] 2022-01-11 06:53
Duplicate of https://github.com/wso2/product-mi-tooling/issues/222. Fixed and shipped to 4.0.1 via update 2

**Closed by sachithKay** 2022-01-11 06:53 UTC
