### ISSUE TITLE
After configuring the RbbitMQ configs in TOML and starting the MI java.lang.ClassCastException generated

### ISSUE THREAD

**Issue by KasunAratthanage** [wso2/micro-integrator#1041] opened 2019-10-09 10:48 UTC
**Description:**
After configuring the RbbitMQ configs in TOML and starting the MI java.lang.ClassCastException generated.

`[2019-10-09 15:19:05,455] FATAL {org.wso2.micro.integrator.core.internal.CoreServerInitializer} - WSO2 Carbon initialization Failed java.lang.ClassCastException: org.apache.axis2.transport.rabbitmq.RabbitMQSender cannot be cast to org.apache.axis2.transport.TransportListener
	at org.apache.axis2.deployment.AxisConfigBuilder.processTransportReceivers(AxisConfigBuilder.java:629)
	at org.apache.axis2.deployment.AxisConfigBuilder.populateConfig(AxisConfigBuilder.java:131)
	at org.wso2.micro.core.CarbonAxisConfigurator.populateAxisConfiguration(CarbonAxisConfigurator.java:282)
	at org.wso2.micro.core.CarbonAxisConfigurator.getAxisConfiguration(CarbonAxisConfigurator.java:170)
	at org.apache.axis2.context.ConfigurationContextFactory.createConfigurationContext(ConfigurationContextFactory.java:64)
	at org.wso2.micro.core.CarbonConfigurationContextFactory.createNewConfigurationContext(CarbonConfigurationContextFactory.java:66)
	at org.wso2.micro.integrator.core.internal.CoreServerInitializer.initializeCarbon(CoreServerInitializer.java:211)
	at org.wso2.micro.integrator.core.internal.CoreServerInitializer.initMIServer(CoreServerInitializer.java:128)
	at org.wso2.micro.integrator.core.internal.Activator.start(Activator.java:82)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:842)
	at org.eclipse.osgi.internal.framework.BundleContextImpl$3.run(BundleContextImpl.java:1)
	at java.security.AccessController.doPrivileged(Native Method)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.startActivator(BundleContextImpl.java:834)
	at org.eclipse.osgi.internal.framework.BundleContextImpl.start(BundleContextImpl.java:791)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.startWorker0(EquinoxBundle.java:1013)
	at org.eclipse.osgi.internal.framework.EquinoxBundle$EquinoxModule.startWorker(EquinoxBundle.java:365)
	at org.eclipse.osgi.container.Module.doStart(Module.java:598)
	at org.eclipse.osgi.container.Module.start(Module.java:462)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel$1.run(ModuleContainer.java:1820)
	at org.eclipse.osgi.internal.framework.EquinoxContainerAdaptor$2$1.execute(EquinoxContainerAdaptor.java:150)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1813)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.incStartLevel(ModuleContainer.java:1770)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.doContainerStartLevel(ModuleContainer.java:1735)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1661)
	at org.eclipse.osgi.container.ModuleContainer$ContainerStartLevel.dispatchEvent(ModuleContainer.java:1)
	at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
	at org.eclipse.osgi.framework.eventmgr.EventManager$EventThread.run(EventManager.java:345)`

**Suggested Labels:**
RabbitMQ

**Suggested Assignees:**

**Affected Product Version:**
WSO2 Micro Integrator 1.1.0

**OS, DB, other environment details and versions:**    
Ubuntu

**Steps to reproduce:**
1.Setup RabbitMQ configs TOML file as following manner.(deployement.toml)

```
[transport.rabbitmq.listener]
name = "rabbitmq"

[transport.rabbitmq.listener.AMQPConnectionFactory]
name = "rabbitMQListener"
parameter.hostname = "localhost"
parameter.port = 5672
parameter.username = "guest"
parameter.password = "guest"

[transport.rabbitmq.sender]
name = "rabbitmq"

[transport.rabbitmq.sender.AMQPConnectionFactory]
name = "rabbitMQSender"
parameter.hostname = "localhost"
parameter.port = 5672
parameter.username = "guest"
parameter.password = "guest

```
2.Run micro-integrator.sh script.

**Comment by madushadhanushka** [comment] 2019-10-09 10:52
**Work around**
This issue was due to issue with template file in <MI_HOME>/repository/resources/conf/templates/conf/axis2/axis2.xml.j2 file. Temporary you can fix this issue by replace following section in axis2.xml.j2 file,
```
    <transportReceiver name="{{transport.rabbitmq.sender.name}}" class="org.apache.axis2.transport.rabbitmq.RabbitMQSender">
        <parameter name="AMQPConnectionFactory" locked="false">
            {% for parameter_key,parameter_value in transport.rabbitmq.sender.AMQPConnectionFactory.parameter.items() %}
            <parameter name="{{parameter_key}}" locked="false">{{parameter_value}}</parameter>
            {% endfor %}
        </parameter>
    </transportReceiver>
```
with following section.
```
    <transportSender name="{{transport.rabbitmq.sender.name}}" class="org.apache.axis2.transport.rabbitmq.RabbitMQSender">
        <parameter name="AMQPConnectionFactory" locked="false">
            {% for parameter_key,parameter_value in transport.rabbitmq.sender.AMQPConnectionFactory.parameter.items() %}
            <parameter name="{{parameter_key}}" locked="false">{{parameter_value}}</parameter>
            {% endfor %}
        </parameter>
    </transportSender>
```

**Comment by madushadhanushka** [comment] 2019-10-10 13:51
Fixed with https://github.com/wso2/micro-integrator/pull/1037

**Comment by sdkottegoda** [comment] 2019-12-06 07:32
Closing since the issue is resolved.

**Closed by sdkottegoda** 2019-12-06 07:32 UTC
Labels: 1.1.0, Severity/Critical, bug
