### ISSUE TITLE
[Coordinated Task Scheduling]Cronjobs do not get executed in the cluster

### ISSUE THREAD

**Issue by isuruuy429** [wso2/micro-integrator#1590] opened 2020-05-27 11:41 UTC
**Steps to reproduce:**
1. Create the following task and the proxy service. 
```
<?xml version="1.0" encoding="UTF-8"?>
<task class="org.apache.synapse.startup.tasks.MessageInjector" group="synapse.simple.quartz" name="Task1" xmlns="http://ws.apache.org/ns/synapse">
    <trigger cron="0 45 16 * * ?"/>
    <property name="injectTo" value="proxy" xmlns:task="http://www.wso2.org/products/wso2commons/tasks"/>
    <property name="proxyName" value="Proxy1" xmlns:task="http://www.wso2.org/products/wso2commons/tasks"/>
    <property name="message" xmlns:task="http://www.wso2.org/products/wso2commons/tasks">
        <request xmlns="">
            <operation>test</operation>
        </request>
    </property>
</task>
```

Proxy
```
<?xml version="1.0" encoding="UTF-8"?>
<proxy name="Proxy1" startOnLoad="true" transports="http https" xmlns="http://ws.apache.org/ns/synapse">
    <target>
        <inSequence>
            <log level="full"/>
            <call>
                <endpoint>
                    <address uri="http://www.mocky.io/v2/5ecb80dd3000005a67ddd670">
                        <suspendOnFailure>
                            <initialDuration>-1</initialDuration>
                            <progressionFactor>-1</progressionFactor>
                            <maximumDuration>0</maximumDuration>
                        </suspendOnFailure>
                        <markForSuspension>
                            <retriesBeforeSuspension>0</retriesBeforeSuspension>
                        </markForSuspension>
                    </address>
                </endpoint>
            </call>
            <drop/>
        </inSequence>
        <outSequence/>
        <faultSequence/>
    </target>
</proxy>
```

2. Deploy the carbon application in a three-node cluster. 

**Expected**: The cron job should be run in the specified time. 
**Actual**: Even though the task gets scheduled in a node, this does not get executed. 

**Affected Product Version:**
https://wso2.org/jenkins/job/products/job/micro-integrator/612/artifact/distribution/target/wso2mi-1.2.0-alpha.zip, 

**OS, DB, other environment details and versions:**    
Ubuntu 18
DB: MSSQL
3 node cluster

**Comment by Nirothipan** [comment] 2020-05-30 15:36
I tried this, but the issue is not reproducible. As per the cron you have given ( 0 45 16 * * ? ) , it is supposed to run At 16:45:00pm every day. Did you verify at that exact time whether this is running or not .

Also you may modify the cron as "* * * * * ?" which runs every second if you need to verify.

**Comment by isuruuy429** [comment] 2020-06-02 12:22
This is working when the cron job was set to run in every second. "* * * * * ?"
It reproduces if you make it to run exactly once. (in a specified time). In stand-alone server, this works.

**Comment by sdkottegoda** [comment] 2020-06-03 10:20
I think this would also be a related issue https://github.com/wso2/product-ei/issues/5132

**Comment by Nirothipan** [comment] 2020-06-11 07:24
I tried with following cron <trigger cron="0 50 12 * * ?"/> in two node cluster 

```bash
[2020-06-11 12:50:00,004]  INFO {LogMediator} - To: , MessageID: urn:uuid:9273ed3b-5a07-420e-b27b-fe62f395cc14, Direction: request, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Body><test>task-1</test></soapenv:Body></soapenv:Envelope>
```

<trigger cron="0 50 12 * * ?"/>

```bash
[2020-06-11 12:53:00,001]  INFO {LogMediator} - To: , MessageID: urn:uuid:ee188c54-601b-4869-88fd-88a25a1e92fb, Direction: request, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Body><test>task-1</test></soapenv:Body></soapenv:Envelope>

```
As pointed in the above issue, it could be for some cron patterns.

**Comment by malakaganga** [comment] 2020-06-11 09:24
Hi @sdkottegoda / @isuruuy429 

We have tried with the exact same cron (0 45 16 * * ?) with the following task

```
<?xml version="1.0" encoding="UTF-8"?>
<task class="org.apache.synapse.startup.tasks.MessageInjector" group="synapse.simple.quartz" name="CronTask" xmlns="http://ws.apache.org/ns/synapse">
    <trigger cron="0 45 16 * * ?"/>
    <property name="proxyName" value="testCronProxy" xmlns:task="http://www.wso2.org/products/wso2commons/tasks"/>
    <property name="message" xmlns:task="http://www.wso2.org/products/wso2commons/tasks">
        <echoString xmlns="">
            <in>CronOnce</in>
        </echoString>
    </property>
    <property name="soapAction" value="mediate" xmlns:task="http://www.wso2.org/products/wso2commons/tasks"/>
    <property name="injectTo" value="proxy" xmlns:task="http://www.wso2.org/products/wso2commons/tasks"/>
</task>
```

And it worked as expected (ran at 16.45 after changing the clock)

Hence we are closing this issue

**Closed by malakaganga** 2020-06-11 09:24 UTC
Labels: Type/Bug

**Comment by malakaganga** [comment] 2020-06-11 09:45
I have tested with cron "0 0 1 * * ?" given in https://github.com/wso2/product-ei/issues/5132
It worked in MI as well
