### ISSUE TITLE
[ DSS ] Support Data Source Deployment as Registry Resource 

### ISSUE THREAD

**Issue by Nirothipan** [wso2/micro-integrator#255] opened 2019-06-06 11:52 UTC
**Description:**
$subject.

In EI when we add a data source, it will be saved as a registry resource.
When we create in Tooling  it is included in Data Source Project and Deployed to the registry when we deploy.

We need to update the deployer to deploy to the file based registry or we need to facilitate creating data source as a registry resource hence it would be deployed when we deploy the carbon app.

**Comment by Nirothipan** [comment] 2019-06-07 11:56
Few Integration tests are commented out due to this in MI. Please un comment them once fixed.

**Comment by sajinieKavindya** [comment] 2019-09-23 11:30
According to the behavior in EI when the data sources are getting deployed via carbon apps, they are not saved as registry resources but will be kept in memory. However, data sources are saved as registry resources only when deploying using the Management Console. 

Following the same approach, in Micro Integrator, deployed data source artifact/s will be kept in memory only (Since we do not support hot deployment in MI).

The data source/s created using data source project in Integration Studio were not getting deployed earlier. 

#810 fixes the above issue.

**Comment by sdkottegoda** [comment] 2019-09-23 12:01
Closing since the issue is fixed

**Closed by sdkottegoda** 2019-09-23 12:01 UTC
Labels: 1.0.0, DSS, Priority/Highest, Type/Improvement, commitment
