### ISSUE TITLE
[CLI Tool] Add new management api data points as commands

### ISSUE THREAD

**Issue by sajithaliyanage** [wso2/micro-integrator#639] opened 2019-08-20 05:24 UTC
**Description:**
Currently, there are newly implemented data points in Management API which are not included in the CLI tool. New data points are list in here - https://github.com/wso2/micro-integrator/issues/603

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by sajithaliyanage** [comment] 2019-08-23 04:20
Related PRs - 
https://github.com/wso2/micro-integrator/pull/647
https://github.com/wso2/micro-integrator/pull/649

**Comment by sdkottegoda** [comment] 2019-09-23 12:05
Closing this since the issue is fixed

**Closed by sdkottegoda** 2019-09-23 12:05 UTC
Labels: Priority/Highest
